// Dev-only data: Card List name (as parseCardList returns it) -> card id, per card type. 183 entries.
// quest_dutch_courage and quest_cheat_code are new ids added in plan 53-05.
export const CARD_ID_MAP = {
  mosjes: {
    "Gandoe, The Unpredictable Wizard": "mosje_gandoe_wizard",
    "Jeffrey, The Strongman": "mosje_jeffrey",
    "Alyssa, The Bulldozer": "mosje_alyssa_bulldozer",
    "Alyssa, Fissa Fissa!": "mosje_alyssa_fissa",
    "AZN Cless, The Wild Card": "mosje_azn_cless",
    "Michelle, Iron Tuk": "mosje_michelle",
    "Parkour West, The Flow Fighter": "mosje_parkour_west",
    "Gandoe, The Destroyer": "mosje_gandoe_destroyer",
    "Ronald, The Master Chef": "mosje_ronald_chef",
    "Ming, The Natural": "mosje_ming_natural",
    "Ming, The Predictor": "mosje_ming_predictor",
    "Martin, The Historian": "mosje_martin_historian",
    "Martin, Senor West": "mosje_martin_senor_west",
    "Coert, The Hawaiian Tech Savant": "mosje_coert_tech",
    "[...], The Hacker": "mosje_hacker",
    "Jeffrey, The Silent Gambler": "mosje_jeffrey_gambler",
    "Chris, The All-Rounder": "mosje_chris",
    "Youri, The Speedrunner": "mosje_youri",
    "Placeholder 1, The Tactician": "mosje_tactician",
    "Placeholder 4, The Drainer": "mosje_drainer",
    "FPS Coert": "mosje_fps_coert",
    "FPS West": "mosje_fps_west",
    "Ronald, The Mastermind": "mosje_ronald_mastermind",
    "Jisca, The Maestro": "mosje_jisca",
    "Tuk, The Healing Spirit": "mosje_tuk_healer",
    "DJ 80/20, The Lucky Mixer": "mosje_dj_8020",
    "Coert, KasteLuck": "mosje_coert_kasteluck",
    "Binti, The Sharp Tongue": "mosje_binti",
    "Cless, The Teacher": "mosje_cless_teacher",
    "Martin, The Precision Driver": "mosje_martin_driver",
    "Tuk \"The Builder\", The Sims Architect": "mosje_tuk_architect",
    "Dancing/DDR Chris": "mosje_chris_ddr",
  },
  quests: {
    "Arm Wrestling": "quest_arm_wrestling",
    "Sprint Race": "quest_sprint_race",
    "Sustained Assault": "quest_sustained_assault",
    "Tough It Out": "quest_tough_it_out",
    "Survive Storm": "quest_survive_storm",
    "Never Give Up": "quest_never_give_up",
    "Parkour Challenge": "quest_parkour_challenge",
    "Endurance Test": "quest_endurance_test",
    "Endure Pain": "quest_endure_pain",
    "Momentum Master": "quest_momentum_master",
    "Ultimate Challenge": "quest_ultimate_challenge",
    "Geen Raad? Vraag Aad!": "quest_geen_raad_vraag_aad",
    "Dutch courage": "quest_dutch_courage",
    "Debug System": "quest_debug_system",
    "Quick Thinking": "quest_quick_thinking",
    "Calculate Odds": "quest_calculate_odds",
    "Late Night Questing": "quest_late_night_questing",
    "Hack Mainframe": "quest_hack_mainframe",
    "Strategy Puzzle": "quest_strategy_puzzle",
    "Synergy Mastery": "quest_synergy_mastery",
    "Build Gadget": "quest_build_gadget",
    "Speed Run": "quest_speed_run",
    "Master Plan": "quest_master_plan",
    "Regelaar": "quest_regelaar",
    "Perfect Timing": "quest_perfect_timing",
    "Cheat code": "quest_cheat_code",
    "Team Building": "quest_team_building",
    "Artistic Expression": "quest_artistic_expression",
    "Inspire Crowd": "quest_inspire_crowd",
    "Improvise!": "quest_improvise",
    "Form Alliance": "quest_form_alliance",
    "Lucky Break": "quest_lucky_break",
    "Negotiation": "quest_negotiation",
    "Larry Temmen Niemand Zeggen": "quest_larry_temmen",
    "Parkeren Delft": "quest_parkeren_delft",
    "Create Masterpiecie": "quest_create_masterpiece",
    "Shotje Obby": "quest_shotje_obby",
    "Leap of Faith": "quest_leap_of_faith",
  },
  piecies: {
    "Kannetje Melk": "piecie_kannetje_melk",
    "Warm Kannetje Melk": "piecie_warm_kannetje_melk",
    "Broodje Döner": "piecie_broodje_doner",
    "Ronald Kip": "piecie_ronald_kip",
    "Chef's Special": "piecie_chefs_special",
    "Varkenspootjes": "piecie_varkenspootjes",
    "Protein Shake": "piecie_protein_shake",
    "Momentum Boost": "piecie_momentum_boost",
    "Nature's Gift": "piecie_eendjes_voeren",
    "Shoettoe": "piecie_energy_surge",
    "Snoeiertje": "piecie_snoeiertje",
    "Te Hard Gaan": "piecie_te_hard_gaan",
    "Super Saiyan Mos": "piecie_super_saiyan_mos",
    "Momentum Diefje": "piecie_momentum_diefje",
    "Jantje Jantje...": "piecie_jantje_jantje",
    "Continuous Assault": "piecie_continuous_assault",
    "MP Hemorrhage": "piecie_mp_hemorrhage",
    "Kleine Taks": "piecie_kleine_taks",
    "Dikke Taks": "piecie_dikke_taks",
    "Harde Didde": "piecie_harde_didde",
    "Klaar Met Jou": "piecie_klaar_met_jou",
    "Zie je die Dingetjes": "piecie_zie_je_die_dingetjes",
    "Bagga of Greed": "piecie_bagga_of_greed",
    "Boosterpackkie": "piecie_boosterpackkie",
    "Perfect Rhythm": "piecie_perfect_rhythm",
    "TemPiecie": "piecie_tempiecie",
    "TweedeKANs": "piecie_tweede_kans",
    "Dubbele Dosis": "piecie_quest_prep",
    "Loaded Dice": "piecie_loaded_dice",
    "Dikke Plaat": "piecie_dikke_plaat",
    "Kan het?!": "piecie_kan_het",
    "Perfect Setup": "piecie_perfect_setup",
    "Redbull": "piecie_redbull",
    "Double Trigger": "piecie_double_trigger",
    "Dubbele Ding": "piecie_dubbele_ding",
    "Chain Reaction": "piecie_chain_reaction",
    "MP Amplifier": "piecie_mp_amplifier",
    "Synergy Field": "piecie_synergy_field",
    "Leipe Swap": "piecie_leipe_swap",
    "Afblijven!": "piecie_afblijven",
    "Laat me chillen!": "piecie_laat_me_chillen",
    "Mosje Shield": "piecie_mosje_shield",
    "Welloe Force": "piecie_welloe_force",
    "Mosje Reborn": "piecie_mosje_reborn",
    "Call of the Welloes": "piecie_call_of_welloes",
    "Slecht Gezet": "piecie_slecht_gezet",
    "Shhh, popo komt!": "piecie_popo_komt",
    "Huisbaas": "piecie_huisbaas",
    "Stookerino": "piecie_stookerino",
    "Those Eyelashes Tho...": "piecie_those_eyelashes",
    "F1 Telemetry Data": "piecie_f1_telemetry",
    "Battle Concert": "piecie_battle_concert",
    "Dingetje toch?!": "piecie_dingetje_toch",
    "Keyboard": "piecie_keyboard",
    "Mouse": "piecie_mouse",
    "Controller": "piecie_controller",
    "Dumbbells": "piecie_dumbbells",
    "Boxing Gloves": "piecie_boxing_gloves",
    "Skipping Rope": "piecie_skipping_rope",
    "Bowie & Stormey": "piecie_bowie_stormey",
    "Tony": "piecie_tony",
    "Gekke Vogels": "piecie_gekke_vogels",
    "KatjeGang": "piecie_katjegang",
    "ViannaPoes": "piecie_vianna_poes",
    "Grammetje Pieter": "piecie_grammetje_pieter",
    "Dikke Jonko": "piecie_dikke_jonko",
    "Affoe": "piecie_affoe",
    "Stripje Bennies": "piecie_stripje_bennies",
    "Tikker": "piecie_tikker",
    "Straffoe": "piecie_straffoe",
    "Larry / Zegeltje": "piecie_larry_zegeltje",
    "Pot of Weed": "piecie_pot_of_weed",
    "Bong Hit Demolition": "piecie_bong_hit_demolition",
  },
  snelle: {
    "Momentum Rush": "snelle_momentum_rush",
    "Bijna Welloe": "snelle_bijna_welloe",
    "Emergency Healings": "snelle_emergency_healings",
    "The Protector": "snelle_the_protector",
    "Perfect Dodge": "snelle_perfect_dodge",
    "Drain Reversal": "snelle_drain_reversal",
    "Not Today!": "snelle_negate_elimination",
    "Ff Haaltje Nemen": "snelle_ff_haaltje_nemen",
    "Lucky Cóin": "snelle_lucky_coin",
    "Sleutelpuntje": "snelle_sleutelpuntje",
    "Je Weet Niet": "snelle_jeweetniet",
    "Counter Strikka": "snelle_counter_strikka",
    "Jammertje Gepakt!": "snelle_jammertje_gepakt",
    "Dubbele Temminks": "snelle_dubbele_temminks",
    "Gevalletje Klakkeloos": "snelle_gevalletje_klakkeloos",
    "Jantje Jantje... Jantje?": "snelle_jantje_jantje_jantje",
    "Chillingsvoorbij!": "snelle_chillingsvoorbij",
    "Jensen!": "snelle_jensen",
    "Frenssen!": "snelle_frenssen",
    "Blensen!": "snelle_blensen",
  },
  places: {
    "The Gym": "place_the_gym",
    "Boxing Ring": "place_boxing_ring",
    "De Box": "place_de_box",
    "Eendjes Voeren": "place_eendjes_voeren",
    "Arcade": "place_arcade",
    "Digital Gaming Stop": "place_digital_gaming_stop",
    "Tesla": "place_tesla",
    "Coert's Caravan": "place_coerts_caravan",
    "Skiffa": "place_skiffa",
    "Bank Chilling": "place_bank_chilling",
    "Delluft": "place_delluft",
    "Quest Haven": "place_quest_haven",
    "Obby #1": "place_obby_1",
    "Zo is Natuur": "place_zo_is_natuur",
    "Drain Zone": "place_drain_zone",
    "Momentum Stabilizer": "place_momentum_stabilizer",
    "The Void": "place_the_void",
    "Welloe Graveyard": "place_welloe_graveyard",
    "Synergy Chamber": "place_synergy_chamber",
    "Dierenasiel": "place_dierenasiel",
  },
};
