// Dev-only: the two Quests new in Card List 2.0, with V4-compatible fields (replaced in Phase 56).
export const NEW_QUEST_BLOCKS = [
  {
    id: 'quest_dutch_courage',
    type: 'QUEST',
    questType: 'GENERAL',
    category: 'Physical',
    requiredMosjeId: null,
    name: 'Dutch courage',
    requirementId: 'quest_req_dutch_courage',
    roll: { trait: 'physical', thresholds: { 1: 5, 2: 4, 3: 3 } },
    requirementDescription: 'Prepared: discard 1 substance Piecie first. Roll: Physical ★=5+, ★★=4+, ★★★=3+',
    successMP: 55,
    failMP: -15,
    description: 'Success: +55 MP. Failure: -15 MP.',
    difficulty: 'LOW',
    isBoosterOnly: false,
    rarity: '★★★',
    flavourText: '',
    artPath: 'assets/quests/placeholder.png',
  },
  {
    id: 'quest_cheat_code',
    type: 'QUEST',
    questType: 'GENERAL',
    category: 'Mental',
    requiredMosjeId: null,
    name: 'Cheat code',
    requirementId: 'quest_req_cheat_code',
    roll: { trait: 'mental', thresholds: { 1: 5, 2: 3, 3: 2 } },
    requirementDescription: 'Prepared: discard 1 Snelle from your hand first. Roll: Mental ★=5+, ★★=3+, ★★★=2+',
    successMP: 60,
    failMP: -20,
    description: 'Success: +60 MP. Failure: -20 MP.',
    difficulty: 'MEDIUM',
    isBoosterOnly: false,
    rarity: '★★★',
    flavourText: '',
    artPath: 'assets/quests/placeholder.png',
  },
];
