// Dev-only: Card List "First you must..." cell text -> short snake id.
export const QUEST_COST_IDS = {
  'Mosje has Physical ★★+': 'physical_2',
  'Level 1 Mosje only': 'level_1_only',
  'Discard 1 ready Piecie': 'discard_ready_piecie',
  'Discard 1 food Piecie (from your hand or a ready one)': 'discard_food_piecie',
  'A Piecie of yours stays in play (any "Stays" card)': 'piecie_stays',
  'Mosje has 80 MP or more': 'mp_80_plus',
  'A Place is in play': 'place_in_play',
  'Discard 1 substance Piecie (from your hand or a ready one)': 'discard_substance_piecie',
  'Mosje has Technical ★★+': 'technical_2',
  'Reveal the top 3 cards of your deck, then put them back': 'reveal_top_3',
  "You also used this Mosje's ability this turn": 'used_ability_this_turn',
  'Activate 1 ready Piecie this turn (pay its Energy)': 'activate_1_ready_piecie',
  'Activate 2 ready Piecies this turn (pay their Energy)': 'activate_2_ready_piecies',
  '3 of your Piecies are face-down': 'three_face_down',
  'You have more Piecies in play than your opponent': 'more_piecies_than_opponent',
  'Mosje has 70 to 80 MP': 'mp_70_to_80',
  'Discard 1 Snelle from your hand': 'discard_snelle',
  'Mosje has Social ★★+': 'social_2',
  'Discard 1 Piecie from your hand': 'discard_hand_piecie',
  '3 or more Piecies of yours are in play': 'three_piecies_in_play',
  "Your Mosjes' total MP is lower than your opponent's": 'lower_total_mp',
};
